resources:
  limits:
    cpu: 100m
    memory: 150Mi
  requests:
    cpu: 100m
    memory: 150Mi
volumes:
  - mountPath: /usr/share/nginx/html
    name: nginx-config-new-ms-2
    volume:
      configMap:
        name: application-config-new-ms-2
        items:
          - key: index-blue.html
            path: index.htm
image:
  name: nginx

prod: true
bluegreen: true
