---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Release.Namespace }}
data:
{{- $configmaps := printf "configs/%s/%s/*" .Values.ms_dir .Release.Namespace }}

{{- range $path, $_ := .Files.Glob $configmaps }}
{{- if not (hasSuffix "values.yaml" $path) }}
  {{ regexReplaceAll "(.*)/" $path "" }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}