{{- if ((.Values.ingress)) -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: {{.Values.name}}
    env: {{.Release.Namespace}}
  name: {{.Values.name}}
  namespace: {{.Release.Namespace}}
spec:
  rules:
  {{- if .Values.bluegreen }}
  - host: argo-rollouts-bluegreen.io  
    http:
      paths:
      - path: /blue-green/active
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{.Values.name}}-active
            port:
              number: {{ ((.Values.service).port) | default 80 }}
      - path: /blue-green/preview
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{.Values.name}}-preview
            port:
              number: {{ ((.Values.service).port) | default 80 }} 
  {{- end }}              
  {{- if .Values.canary }}
  - host: argo-rollouts-canary.io  
    http:
      paths:                            
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ ((.Values.service).port) | default 8080 }}
  {{- end }}             
{{- end }}
