{{- if ((.Values.secrets)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
    env: {{.Release.Namespace}}

stringData:

# shared secrets are located in vault at shared/ path and are the only secrets that need path specified
{{- if .Values.secrets.shared -}}
{{- range .Values.secrets.shared }}
  # parent_path is the path that contains all KV Pairs
  {{ $parent_path := (split "/"  . )._0 }}
  {{ $secret_key  := (split "/"  . )._1 }}
  {{ $secret_key }}: <path:shared/data/{{ $parent_path }}/#{{ $secret_key }}>
{{- end }}

{{- end }}

{{- end }}