resources:
  limits:
    cpu: 100m
    memory: 150Mi
  requests:
    cpu: 100m
    memory: 150Mi
# volumes:
#   - mountPath: /usr/share/nginx/html
#     name: nginx-config-new-ms
#     volume:
#       configMap:
#         name: application-config-new-ms
#         items:
#           - key: index-green.html
#             path: index.htm

image:
  name: argoproj/rollouts-demo:green
service:
  name: http
  port: 8080
  targetPort: 8080

prod: true
canary: true
